version: "3.5"
services:
  iperf:
    image: clearlinux/iperf:latest
    command: "-s"
    container_name: iperf
    network_mode: bridge
    ports:
      - 5201:5201/tcp
      - 5201:5201/udp
    environment:
      - TZ=America/Chicago
    restart: unless-stopped