services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg-rpi
    container_name: mediamtx
    privileged: true
    volumes:
      - ./mediamtx.yaml:/mediamtx.yml
    ports:
      - 8554:8554
      - 1935:1935
      - 8888:8888
      - 8889:8889
      - 8890:8890/udp
      - 8189:8189/udp
    environment:
      - TZ=America/Chicago
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.22.53
    restart: unless-stopped
