---
version: "3"
services:
  syncthing-instance:
    image: syncthing/syncthing:${IMAGE_TAG}
    container_name: syncthing-${INSTANCE}
    hostname: ${SERVERNAME}-syncthing-${INSTANCE}
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /volume1/docker/syncthing/${INSTANCE}/config:/var/syncthing
      - type: bind
        source: ${HOST_PATH1}
        target: ${CONTAINER_PATH1}
    ports:
      - ${PORTHTTP}:8384
      - ${PORTQUIC}:22000/tcp
      - ${PORTQUIC}:22000/udp
      - ${PORTDISC}:21027/udp
    restart: 'unless-stopped'
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
